### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by j0hnk1m** [tobinatore/COVID19-Tracker#8]
Great project! I like how simple everything is with django. I had a question what the difference between the 2 models are (Live and Date) and the decision behind it.

Thanks!

**Comment by tobinatore** [comment]
Thank you! So basically, the **Date** model represents a single day in the timeseries of infections for a country. As you might've seen, it stores the date, number of confirmed infections, deaths and recoveries on that given day, as well as the country the numbers are for. This data is then used when a user selects a country in the table or the dropdown to populate the chart which shows the spread of the disease.

The **Live** model on the other hand contains a (more or less) live overview for every country and is used to populate the table on the left side. It's updated hourly. 

The reasoning behind creating the Live model was that I did not want to send a request to my sources to fetch and process the data every time a user visits my site. This would generate a lot of traffic, whereas right now there's one request an hour. The same thing applies to the Date model. The file containing the timeseries JHU publishes is pretty large and it's not practicable to process the whole file whenever someone wants to see the statistics for a country. So I requested the whole file when I set the application up, stored every date for every country in a Date object and saved those to  a PostgreSQL database.  Now I just need to (automatically) update that database once a day to include the newest numbers and can query it easily whenever a user needs something.

I hope that explanation cleared everything up. If you have more questions ask away!

**Comment by j0hnk1m** [comment]
Thank you for the response! Sorry I'm new to django also, but how do you set it up so that there's only one request an hour? And how did you deploy your app?

**Comment by tobinatore** [comment]
> how do you set it up so that there's only one request an hour?

I chose the rather simple approach of saving the time when the data should be updated in the Live model. When the entries for the table get generated, I populate the "time" field with the current time plus an hour. Now when a user visits the site, the application checks whether the time of the visit is after the scheduled update time or not. If that's the case, the records get updated, if not nothing happens.
Like I said, this is a pretty simple approach. You could also create a cron job to update the database and schedule it to run hourly.

> And how did you deploy your app?

I used DigitalOcean for the hosting. They have some nice guides for setting up a droplet to use Django with a PostgreSQL database and Gunicorn/Nginx. You can find the one I used [here](https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04). But it basically boils down to:   

1. **Setting up a Github repository for the project**
So you can easily clone the project wherever you need it.
2. **Creating a droplet on DigitalOcean**
The cheapest 5$/month Ubuntu one will do (unless you're expecting high loads).
3. **Following the guide I linked**
Which is basically configuring your server, installing dependencies, cloning your project, setting up config files for gunicorn and nginx and testing whether everything worked.
4. **Getting a domain (optional but recommended)**
As far as I know you can actually access the application via the droplet IP, but it's easier for the general public to remember a domain and not some arbitrary numbers. For this step I used one of the free name.com domains from the Github student developer pack.
5. **Setting up the domain to point to your droplets IP**
What I did was create an A record, which redirects covid19app.live to my droplets IP and a CNAME record which acts as an alias and maps www.covid19app.live to the A record. This makes sure that you get to the right site no matter if you're using "www." or not.
6. **Updating the nameservers at the registrar**
Lastly I headed over to name.com and changed the default name.com nameservers to the ones provided by DigitalOcean. This change took a while to take effect and until then the site was not reachable via the domain, just as a heads up.

All in all it's  actually _really_ simple and pretty cheap to run such a web app (it's actually the first one I deployed). The total cost (if I didn't have the DigitalOcean credits and the free domain) would be 21.99$/year for the domain and 60$/year for the droplet or ~6.83$/month for everything.

**Comment by j0hnk1m** [comment]
Nice, thanks for all the info!

**Comment by j0hnk1m** [comment]
What javascript plugin did you use for the map? It looks awesome.

**Comment by tobinatore** [comment]
I used  a jQuery plugin called jVectorMap. You can find it [here](https://jvectormap.com/).

**Comment by j0hnk1m** [comment]
I tried using it, but when I include the tutorial code, all I get is a blank white spot where the map should be. Did you ever have this error?

**Comment by tobinatore** [comment]
To be honest, I don't remember. Have you downloaded one of the world maps from [here](https://jvectormap.com/maps/world/world/)? Without one of these it won't render anything if I recall correctly.
